CREATE TABLE bank_inc.CARD (
    CARD_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID INT,
    EXPIRATION_DATE DATE,
    BALANCE DECIMAL(15, 2),
    STATE VARCHAR(10)
);

CREATE TABLE bank_inc.CARD_AUDIT (
    CARD_AUDIT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CARD_ID BIGINT,
    DATE DATE,
    OLD_BALANCE DECIMAL(15, 2),
    NEW_BALANCE DECIMAL(15, 2),
    OLD_STATE VARCHAR(10),
    NEW_STATE VARCHAR(10),
    FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID)
);

CREATE TABLE bank_inc.TRANSACTION (
    TRANSACTION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CARD_ID BIGINT,
    DATE DATE,
    PRICE DECIMAL(15, 2),
    STATE VARCHAR(10),
    FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID)
);

CREATE TABLE bank_inc.TRANSACTION_AUDIT (
    TRANSACTION_AUDIT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTION_ID BIGINT,
    DATE DATE,
    OLD_STATE VARCHAR(10),
    NEW_STATE VARCHAR(10),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES bank_inc.TRANSACTION(TRANSACTION_ID)
);
