CREATE TABLE bank_inc.CARD (
    CARD_ID BIGINT PRIMARY KEY,
    PRODUCT_ID INT,
    EXPIRATION_DATE DATE,
    BALANCE DECIMAL(15, 2),
    STATE VARCHAR(10)
);

CREATE TABLE bank_inc.CARD_AUDIT (
    CARD_AUDIT_ID BIGINT PRIMARY KEY,
    CARD_ID BIGINT,
    DATE DATE,
    OLD_BALANCE DECIMAL(15, 2),
    NEW_BALANCE DECIMAL(15, 2),
    OLD_STATE VARCHAR(10),
    NEW_STATE VARCHAR(10),
    FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID)
);

CREATE TABLE bank_inc.TRANSACTION (
    TRANSACTION_ID BIGINT PRIMARY KEY,
    CARD_ID BIGINT,
    DATE DATE,
    PRICE DECIMAL(15, 2),
    STATE VARCHAR(10),
    FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID)
);

CREATE TABLE bank_inc.TRANSACTION_AUDIT (
    TRANSACTION_AUDIT_ID BIGINT PRIMARY KEY,
    TRANSACTION_ID BIGINT,
    DATE DATE,
    OLD_STATE VARCHAR(10),
    NEW_STATE VARCHAR(10),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID)
);

ALTER TABLE bank_inc.CARD_AUDIT MODIFY COLUMN CARD_AUDIT_ID BIGINT AUTO_INCREMENT;

ALTER TABLE bank_inc.TRANSACTION_AUDIT
DROP FOREIGN KEY transaction_audit_ibfk_1;

ALTER TABLE bank_inc.TRANSACTION MODIFY COLUMN TRANSACTION_ID BIGINT AUTO_INCREMENT;

ALTER TABLE bank_inc.TRANSACTION_AUDIT
ADD CONSTRAINT transaction_audit_ibfk_1
FOREIGN KEY (TRANSACTION_ID) REFERENCES bank_inc.TRANSACTION(TRANSACTION_ID);

ALTER TABLE bank_inc.TRANSACTION_AUDIT MODIFY COLUMN TRANSACTION_AUDIT_ID BIGINT AUTO_INCREMENT;